import { useState, useEffect } from 'react';

export const useLanguage = () => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    const handleStorageChange = () => {
      const newLanguage = localStorage.getItem('language') || 'en';
      setLanguage(newLanguage);
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const changeLanguage = (newLanguage: string) => {
    localStorage.setItem('language', newLanguage);
    setLanguage(newLanguage);
    document.documentElement.setAttribute('lang', newLanguage);

    // Update font family for different languages
    const body = document.body;
    if (newLanguage === 'hi' || newLanguage === 'mr') {
      // Use Devanagari fonts for Hindi and Marathi
      body.style.fontFamily = '"Noto Sans Devanagari", "Mangal", "Aparajita", system-ui, sans-serif';
    } else {
      // Use default fonts for English
      body.style.fontFamily = 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
    }

    // Trigger storage event for other components
    window.dispatchEvent(new StorageEvent('storage', {
      key: 'language',
      newValue: newLanguage,
      oldValue: language
    }));
  };

  return { language, changeLanguage };
};

export const getTranslatedText = (text: string, language: string = 'en') => {
  const translations = {
    'en': {
      // Core UI
      'Settings': 'Settings',
      'Dark Mode': 'Dark Mode',
      'Light Mode': 'Light Mode',
      'Language': 'Language',
      'Select Language': 'Select Language',
      'Profile': 'Profile',
      'Orders': 'Orders',
      'Logout': 'Logout',
      'Notifications': 'Notifications',
      'Welcome': 'Welcome',
      'Dashboard': 'Dashboard',
      'Cancel': 'Cancel',
      'Save': 'Save',
      'Close': 'Close',
      'Send': 'Send',
      'Submit': 'Submit',
      'Back': 'Back',
      'Next': 'Next',
      'Yes': 'Yes',
      'No': 'No',
      'Edit': 'Edit',
      'Delete': 'Delete',
      'Update': 'Update',
      'View': 'View',
      'Search': 'Search',
      'Clear': 'Clear',
      'Confirm': 'Confirm',
      'Today': 'Today',
      'Loading...': 'Loading...',
      'Success': 'Success',
      'Error': 'Error',

      // Customer Dashboard
      'Quick Order': 'Quick Order',
      'Track Delivery': 'Track Delivery',
      'Your Bills': 'Your Bills',
      'Your Dairyman': 'Your Dairyman',
      'New Order': 'New Order',
      'Order History': 'Order History',
      'Monthly Summary': 'Monthly Summary',
      'Available Milkmen': 'Available Milkmen',
      'Location Recommendations': 'Location Recommendations',
      'Find nearby milkmen': 'Find nearby milkmen',
      'Welcome back': 'Welcome back',
      'Welcome to': 'Welcome to',
      'Choose how you\'d like to use DOOODHWALA today': 'Choose how you\'d like to use DOOODHWALA today',
      'Valued Customer': 'Valued Customer',
      'Manage your daily milk orders and track deliveries': 'Manage your daily milk orders and track deliveries',

      // Products
      'Fresh Milk': 'Fresh Milk',
      'Buffalo Milk': 'Buffalo Milk',
      'Toned Milk': 'Toned Milk',
      'Order Now': 'Order Now',
      'Add to Cart': 'Add to Cart',
      'Place Order': 'Place Order',
      'Total': 'Total',
      'Quantity': 'Quantity',
      'Price': 'Price',
      'per liter': 'per liter',
      'per unit': 'per unit',
      'Order': 'Order',

      // Milkman Dashboard
      'Total Orders': 'Total Orders',
      'Monthly Revenue': 'Monthly Revenue',
      'Active Customers': 'Active Customers',
      'Average Rating': 'Average Rating',
      'Customer Management': 'Customer Management',
      'Service Requests': 'Service Requests',
      'Inventory': 'Inventory',
      'Monthly Earnings': 'Monthly Earnings',
      'Daily Earnings': 'Daily Earnings',
      'Today\'s Deliveries': 'Today\'s Deliveries',
      'Completed': 'Completed',
      'Pending': 'Pending',
      'Customer': 'Customer',
      'Mark Delivered': 'Mark Delivered',
      'Accept Order': 'Accept Order',
      'Accepted': 'Accepted',
      'Chat': 'Chat',
      'Filter': 'Filter',
      'Sort by Route': 'Sort by Route',
      'WELCOME': 'WELCOME',
      'You have': 'You have',
      'deliveries scheduled for today': 'deliveries scheduled for today',
      'No deliveries scheduled for today': 'No deliveries scheduled for today',
      'stops': 'stops',
      'total': 'total',
      'of daily target completed': 'of daily target completed',
      'km': 'km',
      'Details': 'Details',

      // Profile & Forms
      'Complete Profile Setup': 'Complete Profile Setup',
      'Complete Your Profile': 'Complete Your Profile',
      'Let\'s set up your customer profile to get started': 'Let\'s set up your customer profile to get started',
      'Full Name': 'Full Name',
      'Enter your full name': 'Enter your full name',
      'Email Address': 'Email Address',
      'Enter your email address': 'Enter your email address',
      'Email is required for order confirmations and monthly bills': 'Email is required for order confirmations and monthly bills',
      'Setting up...': 'Setting up...',
      'Complete Profile': 'Complete Profile',
      'Getting Location...': 'Getting Location...',
      'Contact Information': 'Contact Information',
      'Delivery Address': 'Delivery Address',
      'Use Current Location': 'Use Current Location',
      'House/Flat Number': 'House/Flat Number',
      'Complete Address': 'Complete Address',
      'Building/Society Name': 'Building/Society Name',
      'Street/Road Name': 'Street/Road Name',
      'Street Name': 'Street Name',
      'Area/Locality': 'Area/Locality',
      'Landmark (Optional)': 'Landmark (Optional)',
      'Landmark': 'Landmark',
      'City': 'City',
      'State': 'State',
      'Pincode': 'Pincode',
      'Country': 'Country',
      'Dairy Products & Pricing': 'Dairy Products & Pricing',
      'Additional Dairy Products (Optional)': 'Additional Dairy Products (Optional)',
      'Set prices for additional products you offer': 'Set prices for additional products you offer',
      'Add Custom Item': 'Add Custom Item',
      'Add Custom Dairy Product': 'Add Custom Dairy Product',
      'Product Name': 'Product Name',
      'Unit': 'Unit',
      'Price (₹)': 'Price (₹)',
      'Add Product': 'Add Product',
      'Custom': 'Custom',
      'Delivery Schedule': 'Delivery Schedule',
      'Add Slot': 'Add Slot',
      'Edit Delivery Slot': 'Edit Delivery Slot',
      'Add New Delivery Slot': 'Add New Delivery Slot',
      'Slot Name': 'Slot Name',
      'Start Time': 'Start Time',
      'End Time': 'End Time',
      'Update Slot': 'Update Slot',

      // Chat & Messages
      'Type a message...': 'Type a message...',
      'Type your message...': 'Type your message...',
      'No messages yet': 'No messages yet',
      'Connecting...': 'Connecting...',
      'Chat with': 'Chat with',
      'Order Request': 'Order Request',
      'Optional note for your order...': 'Optional note for your order...',
      'units': 'units',

      // Status Messages
      'Available': 'Available',
      'Unavailable': 'Unavailable',
      'Status': 'Status',
      'Rating': 'Rating',
      'reviews': 'reviews',
      'Delivery Time': 'Delivery Time',
      'Always on time and friendly!': 'Always on time and friendly!',
      'No customers assigned yet': 'No customers assigned yet',
      'No orders for today': 'No orders for today',
      'No completed orders': 'No completed orders',
      'No deliveries yet': 'No deliveries yet',
      'orders delivered': 'orders delivered',
      'Delivered on': 'Delivered on',
      'Address not available': 'Address not available',
      'Customer Address': 'Customer Address',
      'Product Details': 'Product Details',

      // Bank Account Details
      'Bank Account Details': 'Bank Account Details',
      'Add your bank account details to receive payments directly from customers': 'Add your bank account details to receive payments directly from customers',
      'Account Holder Name': 'Account Holder Name',
      'Account Number': 'Account Number',
      'IFSC Code': 'IFSC Code',
      'Bank Name': 'Bank Name',
      'Branch Name': 'Branch Name',
      'Branch': 'Branch',
      'UPI ID (Optional)': 'UPI ID (Optional)',
      'UPI ID': 'UPI ID',
      'Payment Information': 'Payment Information',
      'Your bank account details are securely stored and used only for receiving payments from customers. We never share this information with third parties.': 'Your bank account details are securely stored and used only for receiving payments from customers. We never share this information with third parties.',
      'Bank account configured for payments': 'Bank account configured for payments',
      'Setup bank account to receive payments': 'Setup bank account to receive payments',
      'Account Type': 'Account Type',
      'Select Account Type': 'Select Account Type',
      'Savings Account': 'Savings Account',
      'Current Account': 'Current Account',
      'Overdraft Account': 'Overdraft Account',
      'Joint Account': 'Joint Account',

      // Inventory Management
      'Stock': 'Stock',
      'In Stock': 'In Stock',
      'Low Stock': 'Low Stock',
      'No Stock': 'No Stock',
      'Out of Stock': 'Out of Stock',
      'Qty': 'Qty',
      'Product Inventory': 'Product Inventory',
      'No products found': 'No products found',
      'Updating inventory...': 'Updating inventory...',
      'Mark Unavailable': 'Mark Unavailable',
      'Mark Available': 'Mark Available',

      // Navigation & Common UI
      'Home': 'Home',
      'Quick Order': 'Quick Order',
      'Track': 'Track',
      'Profile Required': 'Profile Required',
      'Please complete your profile to view orders.': 'Please complete your profile to view orders.',
      'Back to Dashboard': 'Back to Dashboard',
      'Active Orders': 'Active Orders',
      'No Active Orders': 'No Active Orders',
      'Place an order to see it here!': 'Place an order to see it here!',
      'No Payment History': 'No Payment History',
      'Your payment history will appear here.': 'Your payment history will appear here.',
      'Order Summary': 'Order Summary',
      'Completed Orders': 'Completed Orders',

      // Landing Page
      'Fresh Milk, Daily Delivered': 'Fresh Milk, Daily Delivered',
      'Connect with trusted local milkmen for fresh dairy products delivered right to your doorstep.': 'Connect with trusted local milkmen for fresh dairy products delivered right to your doorstep.',
      'Track deliveries, manage orders, and enjoy the convenience of daily milk delivery.': 'Track deliveries, manage orders, and enjoy the convenience of daily milk delivery.',

      // Payment Methods
      'Cash on Delivery': 'Cash on Delivery',
      'Pay when order is delivered': 'Pay when order is delivered',
      'Google Pay': 'Google Pay',
      'Pay with Google Pay': 'Pay with Google Pay',
      'PhonePe': 'PhonePe',
      'Pay with PhonePe': 'Pay with PhonePe',
      'Paytm': 'Paytm',
      'Pay with Paytm': 'Pay with Paytm',

      // Order Status
      'Delivered': 'Delivered',
      'Out for Delivery': 'Out for Delivery',
      'Processing': 'Processing',
      'Confirmed': 'Confirmed',

      // Profile Information
      'Personal Information': 'Personal Information',
      'Profile Information': 'Profile Information',
      'Edit Profile': 'Edit Profile',
      'Name': 'Name',
      'First Name': 'First Name',
      'Last Name': 'Last Name',
      'User ID': 'User ID',
      'Account Created': 'Account Created',
      'Phone Number': 'Phone Number',
      'Address': 'Address',
      'Not provided': 'Not provided',
      'Not available': 'Not available',
      'Verified': 'Verified',
      'Customer Details': 'Customer Details',
      'Assigned Milkman': 'Assigned Milkman',
      'Not assigned': 'Not assigned',
      'Regular Order Quantity': 'Regular Order Quantity',
      'Not set': 'Not set',
      'Auto Payment': 'Auto Payment',
      'Enabled': 'Enabled',
      'Disabled': 'Disabled',
      'Milkman Details': 'Milkman Details',
      'Business Name': 'Business Name',
      'Price per Liter': 'Price per Liter',
      'Verification': 'Verification',
      'Verified Business': 'Verified Business',
      'No ratings yet': 'No ratings yet',
      'reviews': 'reviews',
      'km away': 'km away',
      'Busy': 'Busy',
      'Notify Me': 'Notify Me',
      'Free delivery': 'Free delivery',

      // Chat
      'Chat with Your Dairyman': 'Chat with Your Dairyman',
      'Direct chat interface for placing orders with your assigned dairyman': 'Direct chat interface for placing orders with your assigned dairyman',
      'Close chat': 'Close chat',

      // Business Names (Demo Data)
      'Suresh Dairy Farm': 'Suresh Dairy Farm',
      'Anita Organic Dairy': 'Anita Organic Dairy',
      'Ravi Fresh Milk': 'Ravi Fresh Milk',

      // Your Doodhwala Page
      'Payment Successful!': 'Payment Successful!',
      'Your payment has been processed successfully. Thank you for your order!': 'Your payment has been processed successfully. Thank you for your order!',
      'Profile Required': 'Profile Required',
      'Please complete your profile to view your dairyman.': 'Please complete your profile to view your dairyman.',
      'Your Doodhwala': 'Your Doodhwala',
      'Click to chat and place daily orders': 'Click to chat and place daily orders',
      'Error': 'Error',
      'Please enter both group code and password': 'Please enter both group code and password',
      'Invalid group code format. Expected format: MILK{number}GRP': 'Invalid group code format. Expected format: MILK{number}GRP',
      'Milkman not found for this group code': 'Milkman not found for this group code',
      'Invalid group password': 'Invalid group password',
      'Already Member': 'Already Member',
      'You are already assigned to this milkman\'s group': 'You are already assigned to this milkman\'s group',
      'Success': 'Success',
      'Successfully joined group!': 'Successfully joined group!',
      'Failed to join group': 'Failed to join group',
      'Assignment Error': 'Assignment Error',
      'Failed to assign milkman. Please try again.': 'Failed to assign milkman. Please try again.',
      'Service Request Error': 'Service Request Error',
      'Failed to create service request. Please try again.': 'Failed to create service request. Please try again.',
      'Assignment Successful!': 'Assignment Successful!',
      'milkmen have been assigned with selected services.': 'milkmen have been assigned with selected services.',
      'Failed to assign milkmen. Please try again.': 'Failed to assign milkmen. Please try again.',
      'Settings & Services': 'Settings & Services',
      'View Service Requests': 'View Service Requests',
      'View Order History': 'View Order History',
      'Track Deliveries': 'Track Deliveries',
      'Dairyman Details': 'Dairyman Details',
      'Close': 'Close',
      'Service Details': 'Service Details',
      'Business Information': 'Business Information',
      'Available Products & Services': 'Available Products & Services',
      'Custom Price': 'Custom Price',
      'Out of Stock': 'Out of Stock',
      'Stock': 'Stock',
      'Note': 'Note',
      'About': 'About',
      'Chat & Order': 'Chat & Order',
      'Call Now': 'Call Now',
      'Monthly Orders': 'Monthly Orders',
      'Select Month': 'Select Month',
      'Total Month': 'Total Month',
      'Pay Now': 'Pay Now',
      'Total Amount': 'Total Amount',
      'Total Quantity': 'Total Quantity',
      'Daily Orders': 'Daily Orders',
      'Filter by Product': 'Filter by Product',
      'All Products': 'All Products',
      'No orders found for the selected month.': 'No orders found for the selected month.',
      'Total Orders': 'Total Orders',
      'Product': 'Product',
      'Qty': 'Qty',
      'Price': 'Price',
      'Amount': 'Amount',
      'Customer': 'Customer',
      'Day Total': 'Day Total',
      'Today': 'Today',

      // Service Requests Page
      'Service Requests': 'Service Requests',
      'Track your custom pricing requests': 'Track your custom pricing requests',
      'Back to Your Doodhwala': 'Back to Your Doodhwala',
      'No Service Requests': 'No Service Requests',
      'You haven\'t made any service requests yet. Request custom pricing from your assigned milkman.': 'You haven\'t made any service requests yet. Request custom pricing from your assigned milkman.',
      'Go to Your Doodhwala': 'Go to Your Doodhwala',
      'Service Request': 'Service Request',
      'Requested on': 'Requested on',
      'Requested Services': 'Requested Services',
      'Your Notes': 'Your Notes',
      'Milkman\'s Response': 'Milkman\'s Response',
      'Total Quote': 'Total Quote',
      'Accept Quote': 'Accept Quote',
      'Reject Quote': 'Reject Quote',
      'Pending': 'Pending',
      'Quote Received': 'Quote Received',
      'Accepted': 'Accepted',
      'Rejected': 'Rejected',
      'Available': 'Available',
      'Waiting for milkman response...': 'Waiting for milkman response...',
      'Quote provided on': 'Quote provided on',
      'Accepted on': 'Accepted on',
      'Rejected on': 'Rejected on',
      'Quote Accepted!': 'Quote Accepted!',
      'The milkman has been notified of your acceptance.': 'The milkman has been notified of your acceptance.',
      'Quote Rejected': 'Quote Rejected',
      'The milkman has been notified of your decision.': 'The milkman has been notified of your decision.',
    },
    'hi': {
      // Core UI
      'Settings': 'सेटिंग्स',
      'Dark Mode': 'डार्क मोड',
      'Light Mode': 'लाइट मोड',
      'Language': 'भाषा',
      'Select Language': 'भाषा चुनें',
      'Profile': 'प्रोफ़ाइल',
      'Orders': 'ऑर्डर',
      'Logout': 'लॉगआउट',
      'Notifications': 'सूचनाएं',
      'Welcome': 'स्वागत है',
      'Dashboard': 'डैशबोर्ड',
      'Cancel': 'रद्द करें',
      'Save': 'सहेजें',
      'Close': 'बंद करें',
      'Send': 'भेजें',
      'Submit': 'जमा करें',
      'Back': 'वापस',
      'Next': 'अगला',
      'Yes': 'हाँ',
      'No': 'नहीं',
      'Edit': 'संपादित करें',
      'Delete': 'हटाएं',
      'Update': 'अपडेट करें',
      'View': 'देखें',
      'Search': 'खोजें',
      'Clear': 'साफ करें',
      'Confirm': 'पुष्टि करें',
      'Today': 'आज',
      'Loading...': 'लोड हो रहा है...',
      'Success': 'सफलता',
      'Error': 'त्रुटि',

      // Customer Dashboard
      'Quick Order': 'त्वरित ऑर्डर',
      'Track Delivery': 'डिलीवरी ट्रैक करें',
      'Your Bills': 'आपके बिल',
      'Your Dairyman': 'आपका दूधवाला',
      'New Order': 'नया ऑर्डर',
      'Order History': 'ऑर्डर इतिहास',
      'Monthly Summary': 'मासिक सारांश',
      'Available Milkmen': 'उपलब्ध दूधवाले',
      'Location Recommendations': 'स्थान सुझाव',
      'Find nearby milkmen': 'नजदीकी दूधवाले खोजें',
      'Welcome back': 'वापस स्वागत है',
      'Welcome to': 'में स्वागत',
      'Choose how you\'d like to use DOOODHWALA today': 'आज आप DOOODHWALA का उपयोग कैसे करना चाहते हैं',
      'Valued Customer': 'मूल्यवान ग्राहक',
      'Manage your daily milk orders and track deliveries': 'अपने दैनिक दूध ऑर्डर प्रबंधित करें और डिलीवरी ट्रैक करें',

      // Products
      'Fresh Milk': 'ताजा दूध',
      'Buffalo Milk': 'भैंस का दूध',
      'Toned Milk': 'टोंड मिल्क',
      'Order Now': 'अभी ऑर्डर करें',
      'Add to Cart': 'कार्ट में जोड़ें',
      'Place Order': 'ऑर्डर दें',
      'Total': 'कुल',
      'Quantity': 'मात्रा',
      'Price': 'मूल्य',
      'per liter': 'प्रति लीटर',
      'per unit': 'प्रति यूनिट',
      'Order': 'ऑर्डर',

      // Milkman Dashboard
      'Total Orders': 'कुल ऑर्डर',
      'Monthly Revenue': 'मासिक आय',
      'Active Customers': 'सक्रिय ग्राहक',
      'Average Rating': 'औसत रेटिंग',
      'Customer Management': 'ग्राहक प्रबंधन',
      'Service Requests': 'सेवा अनुरोध',
      'Inventory': 'इन्वेंटरी',
      'Monthly Earnings': 'मासिक कमाई',
      'Daily Earnings': 'दैनिक कमाई',
      'Today\'s Deliveries': 'आज की डिलीवरी',
      'Completed': 'पूर्ण',
      'Pending': 'लंबित',
      'Customer': 'ग्राहक',
      'Mark Delivered': 'डिलीवर किया गया',
      'Accept Order': 'ऑर्डर स्वीकार करें',
      'Accepted': 'स्वीकृत',
      'Chat': 'चैट',
      'Filter': 'फिल्टर',
      'Sort by Route': 'मार्ग के अनुसार क्रमबद्ध करें',
      'WELCOME': 'स्वागत है',
      'You have': 'आपके पास',
      'deliveries scheduled for today': 'आज के लिए डिलीवरी निर्धारित',
      'No deliveries scheduled for today': 'आज के लिए कोई डिलीवरी निर्धारित नहीं',
      'stops': 'स्टॉप',
      'total': 'कुल',
      'of daily target completed': 'दैनिक लक्ष्य पूरा',
      'km': 'किमी',
      'Details': 'विवरण',

      // Profile & Forms
      'Complete Profile Setup': 'प्रोफ़ाइल सेटअप पूरा करें',
      'Complete Your Profile': 'अपना प्रोफ़ाइल पूरा करें',
      'Let\'s set up your customer profile to get started': 'शुरुआत करने के लिए अपना ग्राहक प्रोफ़ाइल सेटअप करें',
      'Full Name': 'पूरा नाम',
      'Enter your full name': 'अपना पूरा नाम दर्ज करें',
      'Email Address': 'ईमेल पता',
      'Enter your email address': 'अपना ईमेल पता दर्ज करें',
      'Email is required for order confirmations and monthly bills': 'ऑर्डर पुष्टि और मासिक बिल के लिए ईमेल आवश्यक है',
      'Setting up...': 'सेटअप हो रहा है...',
      'Complete Profile': 'प्रोफ़ाइल पूरा करें',
      'Getting Location...': 'स्थान प्राप्त कर रहे हैं...',
      'Contact Information': 'संपर्क जानकारी',
      'Delivery Address': 'डिलीवरी पता',
      'Use Current Location': 'वर्तमान स्थान का उपयोग करें',
      'House/Flat Number': 'घर/फ्लैट नंबर',
      'Complete Address': 'पूरा पता',
      'Building/Society Name': 'बिल्डिंग/सोसाइटी का नाम',
      'Street/Road Name': 'सड़क/मार्ग का नाम',
      'Street Name': 'सड़क का नाम',
      'Area/Locality': 'क्षेत्र/इलाका',
      'Landmark (Optional)': 'लैंडमार्क (वैकल्पिक)',
      'Landmark': 'लैंडमार्क',
      'City': 'शहर',
      'State': 'राज्य',
      'Pincode': 'पिनकोड',
      'Country': 'देश',
      'Dairy Products & Pricing': 'डेयरी उत्पाद और मूल्य निर्धारण',
      'Additional Dairy Products (Optional)': 'अतिरिक्त डेयरी उत्पाद (वैकल्पिक)',
      'Set prices for additional products you offer': 'आपके द्वारा पेश किए जाने वाले अतिरिक्त उत्पादों के लिए मूल्य निर्धारित करें',
      'Add Custom Item': 'कस्टम आइटम जोड़ें',
      'Add Custom Dairy Product': 'कस्टम डेयरी उत्पाद जोड़ें',
      'Product Name': 'उत्पाद का नाम',
      'Unit': 'यूनिट',
      'Price (₹)': 'मूल्य (₹)',
      'Add Product': 'उत्पाद जोड़ें',
      'Custom': 'कस्टम',
      'Delivery Schedule': 'डिलीवरी अनुसूची',
      'Add Slot': 'स्लॉट जोड़ें',
      'Edit Delivery Slot': 'डिलीवरी स्लॉट संपादित करें',
      'Add New Delivery Slot': 'नया डिलीवरी स्लॉट जोड़ें',
      'Slot Name': 'स्लॉट का नाम',
      'Start Time': 'शुरुआत का समय',
      'End Time': 'अंत का समय',
      'Update Slot': 'स्लॉट अपडेट करें',

      // Chat & Messages
      'Type a message...': 'मैसेज टाइप करें...',
      'Type your message...': 'अपना मैसेज टाइप करें...',
      'No messages yet': 'अभी तक कोई मैसेज नहीं',
      'Connecting...': 'कनेक्ट हो रहा है...',
      'Chat with': 'चैट करें',
      'Order Request': 'ऑर्डर अनुरोध',
      'Optional note for your order...': 'आपके ऑर्डर के लिए वैकल्पिक नोट...',
      'units': 'यूनिट',

      // Status Messages
      'Available': 'उपलब्ध',
      'Unavailable': 'अनुपलब्ध',
      'Status': 'स्थिति',
      'Rating': 'रेटिंग',
      'reviews': 'समीक्षाएं',
      'Delivery Time': 'डिलीवरी समय',
      'Always on time and friendly!': 'हमेशा समय पर और मैत्रीपूर्ण!',
      'No customers assigned yet': 'अभी तक कोई ग्राहक नियुक्त नहीं',
      'No orders for today': 'आज के लिए कोई ऑर्डर नहीं',
      'No completed orders': 'कोई पूर्ण ऑर्डर नहीं',
      'No deliveries yet': 'अभी तक कोई डिलीवरी नहीं',
      'orders delivered': 'ऑर्डर डिलीवर किए गए',
      'Delivered on': 'डिलीवर किया गया',
      'Address not available': 'पता उपलब्ध नहीं',
      'Customer Address': 'ग्राहक का पता',
      'Product Details': 'उत्पाद विवरण',

      // Bank Account Details
      'Bank Account Details': 'बैंक खाता विवरण',
      'Add your bank account details to receive payments directly from customers': 'ग्राहकों से सीधे भुगतान प्राप्त करने के लिए अपने बैंक खाते का विवरण जोड़ें',
      'Account Holder Name': 'खाता धारक का नाम',
      'Account Number': 'खाता संख्या',
      'IFSC Code': 'आईएफएससी कोड',
      'Bank Name': 'बैंक का नाम',
      'Branch Name': 'शाखा का नाम',
      'Branch': 'शाखा',
      'UPI ID (Optional)': 'यूपीआई आईडी (वैकल्पिक)',
      'UPI ID': 'यूपीआई आईडी',
      'Payment Information': 'भुगतान जानकारी',
      'Your bank account details are securely stored and used only for receiving payments from customers. We never share this information with third parties.': 'आपके बैंक खाते का विवरण सुरक्षित रूप से संग्रहीत है और केवल ग्राहकों से भुगतान प्राप्त करने के लिए उपयोग किया जाता है। हम इस जानकारी को तीसरे पक्ष के साथ कभी साझा नहीं करते हैं।',
      'Bank account configured for payments': 'भुगतान के लिए बैंक खाता कॉन्फ़िगर किया गया',
      'Setup bank account to receive payments': 'भुगतान प्राप्त करने के लिए बैंक खाता सेटअप करें',
      'Account Type': 'खाता प्रकार',
      'Select Account Type': 'खाता प्रकार चुनें',
      'Savings Account': 'बचत खाता',
      'Current Account': 'चालू खाता',
      'Overdraft Account': 'ओवरड्राफ्ट खाता',
      'Joint Account': 'संयुक्त खाता',

      // Inventory Management
      'Stock': 'स्टॉक',
      'In Stock': 'स्टॉक में है',
      'Low Stock': 'कम स्टॉक',
      'No Stock': 'स्टॉक नहीं',
      'Out of Stock': 'स्टॉक खत्म',
      'Qty': 'मात्रा',
      'Product Inventory': 'उत्पाद इन्वेंटरी',
      'No products found': 'कोई उत्पाद नहीं मिला',
      'Updating inventory...': 'इन्वेंटरी अपडेट हो रही है...',
      'Mark Unavailable': 'अनुपलब्ध करें',
      'Mark Available': 'उपलब्ध करें',

      // Navigation & Common UI
      'Home': 'होम',
      'Quick Order': 'त्वरित ऑर्डर',
      'Track': 'ट्रैक करें',
      'Profile Required': 'प्रोफ़ाइल आवश्यक',
      'Please complete your profile to view orders.': 'ऑर्डर देखने के लिए कृपया अपना प्रोफ़ाइल पूरा करें।',
      'Back to Dashboard': 'डैशबोर्ड पर वापस जाएं',
      'Active Orders': 'सक्रिय ऑर्डर',
      'No Active Orders': 'कोई सक्रिय ऑर्डर नहीं',
      'Place an order to see it here!': 'यहां देखने के लिए ऑर्डर दें!',
      'No Payment History': 'कोई भुगतान इतिहास नहीं',
      'Your payment history will appear here.': 'आपका भुगतान इतिहास यहां दिखाई देगा।',
      'Order Summary': 'ऑर्डर सारांश',
      'Completed Orders': 'पूर्ण ऑर्डर',

      // Profile Information
      'Personal Information': 'व्यक्तिगत जानकारी',
      'Profile Information': 'प्रोफ़ाइल जानकारी',
      'Edit Profile': 'प्रोफ़ाइल संपादित करें',
      'Name': 'नाम',
      'First Name': 'पहला नाम',
      'Last Name': 'अंतिम नाम',
      'User ID': 'उपयोगकर्ता आईडी',
      'Account Created': 'खाता बनाया गया',
      'Phone Number': 'फोन नंबर',
      'Address': 'पता',
      'Not provided': 'प्रदान नहीं किया गया',
      'Not available': 'उपलब्ध नहीं',
      'Verified': 'सत्यापित',
      'Customer Details': 'ग्राहक विवरण',
      'Assigned Milkman': 'निर्दिष्ट दूधवाला',
      'Not assigned': 'असाइन नहीं किया गया',
      'Regular Order Quantity': 'नियमित ऑर्डर मात्रा',
      'Not set': 'सेट नहीं है',
      'Auto Payment': 'ऑटो पेमेंट',
      'Enabled': 'सक्षम',
      'Disabled': 'अक्षम',
      'Milkman Details': 'दूधवाला विवरण',
      'Business Name': 'व्यापार का नाम',
      'Price per Liter': 'प्रति लीटर कीमत',
      'Verification': 'सत्यापन',
      'Verified Business': 'सत्यापित व्यापार',
      'No ratings yet': 'अभी तक कोई रेटिंग नहीं',
      'reviews': 'समीक्षाएं',
      'km away': 'किमी दूर',
      'Busy': 'व्यस्त',
      'Notify Me': 'मुझे सूचित करें',
      'Free delivery': 'मुफ्त डिलीवरी',

      // Chat
      'Chat with Your Dairyman': 'अपने दूधवाले से चैट करें',
      'Direct chat interface for placing orders with your assigned dairyman': 'आपके निर्दिष्ट दूधवाले के साथ ऑर्डर देने के लिए सीधी चैट',
      'Close chat': 'चैट बंद करें',

      // Business Names (Demo Data)
      'Suresh Dairy Farm': 'सुरेश डेयरी फार्म',
      'Anita Organic Dairy': 'अनिता ऑर्गेनिक डेयरी',
      'Ravi Fresh Milk': 'रवि फ्रेश मिल्क',

      // Your Doodhwala Page
      'Payment Successful!': 'भुगतान सफल!',
      'Your payment has been processed successfully. Thank you for your order!': 'आपका भुगतान सफलतापूर्वक प्रोसेस हो गया है। आपके ऑर्डर के लिए धन्यवाद!',
      'Profile Required': 'प्रोफाइल आवश्यक',
      'Please complete your profile to view your dairyman.': 'अपने दूधवाले को देखने के लिए कृपया अपना प्रोफाइल पूरा करें।',
      'Your Doodhwala': 'आपका दूधवाला',
      'Click to chat and place daily orders': 'चैट करने और दैनिक ऑर्डर देने के लिए क्लिक करें',
      'Error': 'त्रुटि',
      'Please enter both group code and password': 'कृपया ग्रुप कोड और पासवर्ड दोनों दर्ज करें',
      'Invalid group code format. Expected format: MILK{number}GRP': 'अमान्य ग्रुप कोड प्रारूप। अपेक्षित प्रारूप: MILK{संख्या}GRP',
      'Milkman not found for this group code': 'इस ग्रुप कोड के लिए दूधवाला नहीं मिला',
      'Invalid group password': 'अमान्य ग्रुप पासवर्ड',
      'Already Member': 'पहले से सदस्य',
      'You are already assigned to this milkman\'s group': 'आप पहले से ही इस दूधवाले के ग्रुप में असाइन हैं',
      'Success': 'सफल',
      'Successfully joined group!': 'सफलतापूर्वक ग्रुप में शामिल हो गए!',
      'Failed to join group': 'ग्रुप में शामिल होने में विफल',
      'Assignment Error': 'असाइनमेंट त्रुटि',
      'Failed to assign milkman. Please try again.': 'दूधवाला असाइन करने में विफल। कृपया पुनः प्रयास करें।',
      'Service Request Error': 'सेवा अनुरोध त्रुटि',
      'Failed to create service request. Please try again.': 'सेवा अनुरोध बनाने में विफल। कृपया पुनः प्रयास करें।',
      'Assignment Successful!': 'असाइनमेंट सफल!',
      'milkmen have been assigned with selected services.': 'दूधवालों को चयनित सेवाओं के साथ असाइन कर दिया गया है।',
      'Failed to assign milkmen. Please try again.': 'दूधवालों को असाइन करने में विफल। कृपया पुनः प्रयास करें।',
      'Settings & Services': 'सेटिंग्स और सेवाएं',
      'View Service Requests': 'सेवा अनुरोध देखें',
      'View Order History': 'ऑर्डर इतिहास देखें',
      'Track Deliveries': 'डिलीवरी ट्रैक करें',
      'Dairyman Details': 'दूधवाले की जानकारी',
      'Close': 'बंद करें',
      'Service Details': 'सेवा विवरण',
      'Business Information': 'व्यापार की जानकारी',
      'Available Products & Services': 'उपलब्ध उत्पाद और सेवाएं',
      'Custom Price': 'कस्टम कीमत',
      'Out of Stock': 'स्टॉक में नहीं',
      'Stock': 'स्टॉक',
      'Note': 'नोट',
      'About': 'के बारे में',
      'Chat & Order': 'चैट और ऑर्डर',
      'Call Now': 'अभी कॉल करें',
      'Monthly Orders': 'मासिक ऑर्डर',
      'Select Month': 'महीना चुनें',
      'Total Month': 'कुल महीना',
      'Pay Now': 'अभी भुगतान करें',
      'Total Amount': 'कुल राशि',
      'Total Quantity': 'कुल मात्रा',
      'Daily Orders': 'दैनिक ऑर्डर',
      'Filter by Product': 'उत्पाद के अनुसार फ़िल्टर करें',
      'All Products': 'सभी उत्पाद',
      'No orders found for the selected month.': 'चयनित महीने के लिए कोई ऑर्डर नहीं मिला।',
      'Total Orders': 'कुल ऑर्डर',
      'Product': 'उत्पाद',
      'Qty': 'मात्रा',
      'Price': 'कीमत',
      'Amount': 'राशि',
      'Customer': 'ग्राहक',
      'Day Total': 'दिन का कुल',
      'Today': 'आज',

      // Service Requests Page
      'Service Requests': 'सेवा अनुरोध',
      'Track your custom pricing requests': 'अपने कस्टम मूल्य निर्धारण अनुरोधों को ट्रैक करें',
      'Back to Your Doodhwala': 'अपने दूधवाले पर वापस जाएं',
      'No Service Requests': 'कोई सेवा अनुरोध नहीं',
      'You haven\'t made any service requests yet. Request custom pricing from your assigned milkman.': 'आपने अभी तक कोई सेवा अनुरोध नहीं किया है। अपने निर्दिष्ट दूधवाले से कस्टम मूल्य निर्धारण का अनुरोध करें।',
      'Go to Your Doodhwala': 'अपने दूधवाले के पास जाएं',
      'Service Request': 'सेवा अनुरोध',
      'Requested on': 'अनुरोध किया गया',
      'Requested Services': 'अनुरोधित सेवाएं',
      'Your Notes': 'आपकी टिप्पणियां',
      'Milkman\'s Response': 'दूधवाले की प्रतिक्रिया',
      'Total Quote': 'कुल उद्धरण',
      'Accept Quote': 'उद्धरण स्वीकार करें',
      'Reject Quote': 'उद्धरण अस्वीकार करें',
      'Pending': 'लंबित',
      'Quote Received': 'उद्धरण प्राप्त',
      'Accepted': 'स्वीकृत',
      'Rejected': 'अस्वीकृत',
      'Available': 'उपलब्ध',
      'Waiting for milkman response...': 'दूधवाले की प्रतिक्रिया की प्रतीक्षा में...',
      'Quote provided on': 'उद्धरण प्रदान किया गया',
      'Accepted on': 'स्वीकार किया गया',
      'Rejected on': 'अस्वीकार किया गया',
      'Quote Accepted!': 'उद्धरण स्वीकार!',
      'The milkman has been notified of your acceptance.': 'दूधवाले को आपकी स्वीकृति की सूचना दे दी गई है।',
      'Quote Rejected': 'उद्धरण अस्वीकार',
      'The milkman has been notified of your decision.': 'दूधवाले को आपके निर्णय की सूचना दे दी गई है।',
    },
    'mr': {
      // Core UI
      'Settings': 'सेटिंग्स',
      'Dark Mode': 'डार्क मोड',
      'Light Mode': 'लाइट मोड',
      'Language': 'भाषा',
      'Select Language': 'भाषा निवडा',
      'Profile': 'प्रोफाइल',
      'Orders': 'ऑर्डर',
      'Logout': 'लॉगआउट',
      'Notifications': 'सूचना',
      'Welcome': 'स्वागत',
      'Dashboard': 'डॅशबोर्ड',
      'Cancel': 'रद्द करा',
      'Save': 'सेव्ह करा',
      'Close': 'बंद करा',
      'Send': 'पाठवा',
      'Submit': 'सबमिट करा',
      'Back': 'मागे',
      'Next': 'पुढे',
      'Yes': 'होय',
      'No': 'नाही',
      'Edit': 'संपादित करा',
      'Delete': 'हटवा',
      'Update': 'अपडेट करा',
      'View': 'पहा',
      'Search': 'शोधा',
      'Clear': 'साफ करा',
      'Confirm': 'पुष्टी करा',
      'Today': 'आज',
      'Loading...': 'लोड होत आहे...',
      'Success': 'यशस्वी',
      'Error': 'त्रुटी',

      // Customer Dashboard
      'Quick Order': 'त्वरित ऑर्डर',
      'Track Delivery': 'डिलिव्हरी ट्रॅक करा',
      'Your Bills': 'तुमची बिले',
      'Your Dairyman': 'तुमचा दूधवाला',
      'New Order': 'नवीन ऑर्डर',
      'Order History': 'ऑर्डर इतिहास',
      'Monthly Summary': 'मासिक सारांश',
      'Available Milkmen': 'उपलब्ध दूधवाले',
      'Location Recommendations': 'स्थान शिफारसी',
      'Find nearby milkmen': 'जवळचे दूधवाले शोधा',
      'Welcome back': 'परत स्वागत',
      'Welcome to': 'मध्ये स्वागत',
      'Choose how you\'d like to use DOOODHWALA today': 'आज तुम्ही DOOODHWALA कसा वापरू इच्छिता',
      'Valued Customer': 'मूल्यवान ग्राहक',
      'Manage your daily milk orders and track deliveries': 'तुमचे दैनिक दूध ऑर्डर व्यवस्थापित करा आणि डिलिव्हरी ट्रॅक करा',

      // Products
      'Fresh Milk': 'ताजे दूध',
      'Buffalo Milk': 'म्हशीचे दूध',
      'Toned Milk': 'टोंड मिल्क',
      'Order Now': 'आता ऑर्डर करा',
      'Add to Cart': 'कार्टमध्ये जोडा',
      'Place Order': 'ऑर्डर द्या',
      'Total': 'एकूण',
      'Quantity': 'प्रमाण',
      'Price': 'किंमत',
      'per liter': 'प्रति लीटर',
      'per unit': 'प्रति युनिट',
      'Order': 'ऑर्डर',

      // Milkman Dashboard
      'Total Orders': 'एकूण ऑर्डर',
      'Monthly Revenue': 'मासिक महसूल',
      'Active Customers': 'सक्रिय ग्राहक',
      'Average Rating': 'सरासरी रेटिंग',
      'Customer Management': 'ग्राहक व्यवस्थापन',
      'Service Requests': 'सेवा विनंत्या',
      'Inventory': 'इन्व्हेंटरी',
      'Monthly Earnings': 'मासिक कमाई',
      'Daily Earnings': 'दैनिक कमाई',
      'Today\'s Deliveries': 'आजची डिलिव्हरी',
      'Completed': 'पूर्ण',
      'Pending': 'प्रलंबित',
      'Customer': 'ग्राहक',
      'Mark Delivered': 'डिलिव्हर केले',
      'Accept Order': 'ऑर्डर स्वीकारा',
      'Accepted': 'स्वीकृत',
      'Chat': 'चॅट',
      'Filter': 'फिल्टर',
      'Sort by Route': 'मार्गानुसार क्रमवारी',
      'WELCOME': 'स्वागत',
      'You have': 'तुमच्याकडे',
      'deliveries scheduled for today': 'आजसाठी डिलिव्हरी निर्धारित',
      'No deliveries scheduled for today': 'आजसाठी कोणतीही डिलिव्हरी निर्धारित नाही',
      'stops': 'स्टॉप',
      'total': 'एकूण',
      'of daily target completed': 'दैनिक लक्ष्य पूर्ण',
      'km': 'किमी',
      'Details': 'तपशील',

      // Profile & Forms
      'Complete Profile Setup': 'प्रोफाइल सेटअप पूर्ण करा',
      'Complete Your Profile': 'तुमचे प्रोफाइल पूर्ण करा',
      'Let\'s set up your customer profile to get started': 'सुरुवात करण्यासाठी तुमचे ग्राहक प्रोफाइल सेटअप करू या',
      'Full Name': 'पूर्ण नाव',
      'Enter your full name': 'तुमचे पूर्ण नाव लिहा',
      'Email Address': 'ईमेल पत्ता',
      'Enter your email address': 'तुमचा ईमेल पत्ता लिहा',
      'Email is required for order confirmations and monthly bills': 'ऑर्डर पुष्टी आणि मासिक बिलांसाठी ईमेल आवश्यक आहे',
      'Setting up...': 'सेटअप होत आहे...',
      'Complete Profile': 'प्रोफाइल पूर्ण करा',
      'Getting Location...': 'स्थान मिळवत आहे...',
      'Contact Information': 'संपर्क माहिती',
      'Delivery Address': 'डिलिव्हरी पत्ता',
      'Use Current Location': 'सध्याचे स्थान वापरा',
      'House/Flat Number': 'घर/फ्लॅट नंबर',
      'Complete Address': 'पूर्ण पत्ता',
      'Building/Society Name': 'इमारत/सोसायटीचे नाव',
      'Street/Road Name': 'रस्ता/मार्गाचे नाव',
      'Street Name': 'रस्त्याचे नाव',
      'Area/Locality': 'क्षेत्र/परिसर',
      'Landmark (Optional)': 'लँडमार्क (पर्यायी)',
      'Landmark': 'लँडमार्क',
      'City': 'शहर',
      'State': 'राज्य',
      'Pincode': 'पिनकोड',
      'Country': 'देश',
      'Dairy Products & Pricing': 'डेअरी उत्पादने आणि किंमत',
      'Additional Dairy Products (Optional)': 'अतिरिक्त डेअरी उत्पादने (पर्यायी)',
      'Set prices for additional products you offer': 'तुम्ही ऑफर करत असलेल्या अतिरिक्त उत्पादनांसाठी किंमत सेट करा',
      'Add Custom Item': 'कस्टम आयटम जोडा',
      'Add Custom Dairy Product': 'कस्टम डेअरी उत्पादन जोडा',
      'Product Name': 'उत्पादनाचे नाव',
      'Unit': 'युनिट',
      'Price (₹)': 'किंमत (₹)',
      'Add Product': 'उत्पादन जोडा',
      'Custom': 'कस्टम',
      'Delivery Schedule': 'डिलिव्हरी वेळापत्रक',
      'Add Slot': 'स्लॉट जोडा',
      'Edit Delivery Slot': 'डिलिव्हरी स्लॉट संपादित करा',
      'Add New Delivery Slot': 'नवीन डिलिव्हरी स्लॉट जोडा',
      'Slot Name': 'स्लॉटचे नाव',
      'Start Time': 'सुरुवातीची वेळ',
      'End Time': 'अंतिम वेळ',
      'Update Slot': 'स्लॉट अपडेट करा',

      // Chat & Messages
      'Type a message...': 'मेसेज टाइप करा...',
      'Type your message...': 'तुमचा मेसेज टाइप करा...',
      'No messages yet': 'अजूनही कोणते मेसेज नाहीत',
      'Connecting...': 'कनेक्ट होत आहे...',
      'Chat with': 'चॅट करा',
      'Order Request': 'ऑर्डर विनंती',
      'Optional note for your order...': 'तुमच्या ऑर्डरसाठी पर्यायी नोंद...',
      'units': 'युनिट',

      // Status Messages
      'Available': 'उपलब्ध',
      'Unavailable': 'अनुपलब्ध',
      'Status': 'स्थिती',
      'Rating': 'रेटिंग',
      'reviews': 'समीक्षा',
      'Delivery Time': 'डिलिव्हरी वेळ',
      'Always on time and friendly!': 'नेहमी वेळेवर आणि मैत्रीपूर्ण!',
      'No customers assigned yet': 'अजूनही कोणते ग्राहक नियुक्त नाहीत',
      'No orders for today': 'आजसाठी कोणतेही ऑर्डर नाहीत',
      'No completed orders': 'कोणतेही पूर्ण ऑर्डर नाहीत',
      'No deliveries yet': 'अजूनही कोणतीही डिलिव्हरी नाही',
      'orders delivered': 'ऑर्डर डिलिव्हर केले',
      'Delivered on': 'डिलिव्हर केले',
      'Address not available': 'पत्ता उपलब्ध नाही',
      'Customer Address': 'ग्राहक पत्ता',
      'Product Details': 'उत्पाद तपशील',

      // Bank Account Details
      'Bank Account Details': 'बँक खात्याचे तपशील',
      'Add your bank account details to receive payments directly from customers': 'ग्राहकांकडून थेट पेमेंट मिळवण्यासाठी तुमच्या बँक खात्याचे तपशील जोडा',
      'Account Holder Name': 'खाते धारकाचे नाव',
      'Account Number': 'खाते क्रमांक',
      'IFSC Code': 'आयएफएससी कोड',
      'Bank Name': 'बँकेचे नाव',
      'Branch Name': 'शाखेचे नाव',
      'Branch': 'शाखा',
      'UPI ID (Optional)': 'यूपीआय आयडी (पर्यायी)',
      'UPI ID': 'यूपीआय आयडी',
      'Payment Information': 'पेमेंट माहिती',
      'Your bank account details are securely stored and used only for receiving payments from customers. We never share this information with third parties.': 'तुमच्या बँक खात्याचे तपशील सुरक्षितपणे साठवले जातात आणि फक्त ग्राहकांकडून पेमेंट मिळवण्यासाठी वापरले जातात. आम्ही ही माहिती कधीही तृतीय पक्षांसह शेअर करत नाही.',
      'Bank account configured for payments': 'पेमेंटसाठी बँक खाते कॉन्फिगर केले',
      'Setup bank account to receive payments': 'पेमेंट मिळवण्यासाठी बँक खाते सेटअप करा',
      'Account Type': 'खात्याचा प्रकार',
      'Select Account Type': 'खात्याचा प्रकार निवडा',
      'Savings Account': 'बचत खाते',
      'Current Account': 'चालू खाते',
      'Overdraft Account': 'ओव्हरड्राफ्ट खाते',
      'Joint Account': 'संयुक्त खाते',

      // Inventory Management
      'Stock': 'स्टॉक',
      'In Stock': 'स्टॉकमध्ये आहे',
      'Low Stock': 'कमी स्टॉक',
      'No Stock': 'स्टॉक नाही',
      'Out of Stock': 'स्टॉक संपला',
      'Qty': 'प्रमाण',
      'Product Inventory': 'उत्पाद इन्व्हेंटरी',
      'No products found': 'कोणतेही उत्पादन सापडले नाही',
      'Updating inventory...': 'इन्व्हेंटरी अपडेट होत आहे...',
      'Mark Unavailable': 'अनुपलब्ध करा',
      'Mark Available': 'उपलब्ध करा',

      // Navigation & Common UI
      'Home': 'होम',
      'Quick Order': 'त्वरित ऑर्डर',
      'Track': 'ट्रॅक करा',
      'Profile Required': 'प्रोफाइल आवश्यक',
      'Please complete your profile to view orders.': 'ऑर्डर पाहण्यासाठी कृपया तुमची प्रोफाइल पूर्ण करा.',
      'Back to Dashboard': 'डॅशबोर्डवर परत या',
      'Active Orders': 'सक्रिय ऑर्डर',
      'No Active Orders': 'कोणतेही सक्रिय ऑर्डर नाहीत',
      'Place an order to see it here!': 'येथे पाहण्यासाठी ऑर्डर द्या!',
      'No Payment History': 'कोणतेही पेमेंट इतिहास नाही',
      'Your payment history will appear here.': 'तुमचा पेमेंट इतिहास येथे दिसेल.',
      'Order Summary': 'ऑर्डर सारांश',
      'Completed Orders': 'पूर्ण केलेले ऑर्डर',

      // Payment Methods
      'Cash on Delivery': 'डिलिव्हरीवर रोकड',
      'Pay when order is delivered': 'ऑर्डर डिलिव्हर झाल्यावर पैसे द्या',
      'Google Pay': 'गूगल पे',
      'Pay with Google Pay': 'गूगल पे ने पैसे द्या',
      'PhonePe': 'फोनपे',
      'Pay with PhonePe': 'फोनपे ने पैसे द्या',

      // Order Status
      'Delivered': 'डिलिव्हर झाले',
      'Out for Delivery': 'डिलिव्हरीसाठी निघाले',
      'Processing': 'प्रक्रिया सुरू आहे',
      'Confirmed': 'पुष्ट केले',

      // Profile Information
      'Personal Information': 'वैयक्तिक माहिती',
      'Profile Information': 'प्रोफाइल माहिती',
      'Edit Profile': 'प्रोफाइल संपादित करा',
      'Name': 'नाव',
      'First Name': 'पहिले नाव',
      'Last Name': 'आडनाव',
      'User ID': 'वापरकर्ता आयडी',
      'Account Created': 'खाते तयार केले',
      'Phone Number': 'फोन नंबर',
      'Address': 'पत्ता',
      'Not provided': 'दिले नाही',
      'Not available': 'उपलब्ध नाही',
      'Verified': 'सत्यापित',
      'Customer Details': 'ग्राहकाची माहिती',
      'Assigned Milkman': 'नियुक्त केलेला दूधवाला',
      'Not assigned': 'नियुक्त केले नाही',
      'Regular Order Quantity': 'नियमित ऑर्डर प्रमाण',
      'Not set': 'सेट केले नाही',
      'Auto Payment': 'ऑटो पेमेंट',
      'Enabled': 'सक्षम',
      'Disabled': 'अक्षम',
      'Milkman Details': 'दूधवाल्याची माहिती',
      'Business Name': 'व्यवसायाचे नाव',
      'Price per Liter': 'प्रति लिटर किंमत',
      'Verification': 'सत्यापन',
      'Verified Business': 'सत्यापित व्यवसाय',
      'No ratings yet': 'अजून कोणतेही रेटिंग नाही',
      'reviews': 'समीक्षा',
      'km away': 'किमी दूर',
      'Busy': 'व्यस्त',
      'Notify Me': 'मला कळवा',
      'Free delivery': 'मोफत डिलिव्हरी',

      // Chat
      'Chat with Your Dairyman': 'तुमच्या दूधवाल्याशी चॅट करा',
      'Direct chat interface for placing orders with your assigned dairyman': 'तुमच्या नियुक्त दूधवाल्यासोबत ऑर्डर देण्यासाठी थेट चॅट',
      'Close chat': 'चॅट बंद करा',

      // Business Names (Demo Data)
      'Suresh Dairy Farm': 'सुरेश डेअरी फार्म',
      'Anita Organic Dairy': 'अनिता ऑरगॅनिक डेअरी',
      'Ravi Fresh Milk': 'रवि फ्रेश मिल्क',

      // Your Doodhwala Page
      'Payment Successful!': 'पेमेंट यशस्वी!',
      'Your payment has been processed successfully. Thank you for your order!': 'तुमची पेमेंट यशस्वीपणे प्रक्रिया झाली आहे। तुमच्या ऑर्डरबद्दल धन्यवाद!',
      'Profile Required': 'प्रोफाइल आवश्यक',
      'Please complete your profile to view your dairyman.': 'तुमच्या दूधवाल्याला पाहण्यासाठी कृपया तुमचे प्रोफाइल पूर्ण करा।',
      'Your Doodhwala': 'तुमचा दूधवाला',
      'Click to chat and place daily orders': 'चॅट करण्यासाठी आणि दैनंदिन ऑर्डर देण्यासाठी क्लिक करा',
      'Error': 'त्रुटी',
      'Please enter both group code and password': 'कृपया ग्रुप कोड आणि पासवर्ड दोन्ही टाका',
      'Invalid group code format. Expected format: MILK{number}GRP': 'चुकीचे ग्रुप कोड फॉरमॅट। अपेक्षित फॉरमॅट: MILK{संख्या}GRP',
      'Milkman not found for this group code': 'या ग्रुप कोडसाठी दूधवाला मिळाला नाही',
      'Invalid group password': 'चुकीचा ग्रुप पासवर्ड',
      'Already Member': 'आधीच सदस्य',
      'You are already assigned to this milkman\'s group': 'तुम्ही आधीपासूनच या दूधवाल्याच्या ग्रुपमध्ये असाइन आहात',
      'Success': 'यशस्वी',
      'Successfully joined group!': 'यशस्वीपणे ग्रुपमध्ये सामील झाला!',
      'Failed to join group': 'ग्रुपमध्ये सामील होण्यात अयशस्वी',
      'Assignment Error': 'असाइनमेंट त्रुटी',
      'Failed to assign milkman. Please try again.': 'दूधवाला असाइन करण्यात अयशस्वी। कृपया पुन्हा प्रयत्न करा।',
      'Service Request Error': 'सेवा विनंती त्रुटी',
      'Failed to create service request. Please try again.': 'सेवा विनंती तयार करण्यात अयशस्वी। कृपया पुन्हा प्रयत्न करा।',
      'Assignment Successful!': 'असाइनमेंट यशस्वी!',
      'milkmen have been assigned with selected services.': 'दूधवाल्यांना निवडलेल्या सेवांसह असाइन केले गेले आहे।',
      'Failed to assign milkmen. Please try again.': 'दूधवाल्यांना असाइन करण्यात अयशस्वी। कृपया पुन्हा प्रयत्न करा।',
      'Settings & Services': 'सेटिंग्ज आणि सेवा',
      'View Service Requests': 'सेवा विनंती पहा',
      'View Order History': 'ऑर्डर इतिहास पहा',
      'Track Deliveries': 'डिलिव्हरी ट्रॅक करा',
      'Dairyman Details': 'दूधवाल्याची माहिती',
      'Close': 'बंद करा',
      'Service Details': 'सेवा तपशील',
      'Business Information': 'व्यवसायाची माहिती',
      'Available Products & Services': 'उपलब्ध उत्पादने आणि सेवा',
      'Custom Price': 'कस्टम किंमत',
      'Out of Stock': 'स्टॉक नाही',
      'Stock': 'स्टॉक',
      'Note': 'नोंद',
      'About': 'बद्दल',
      'Chat & Order': 'चॅट आणि ऑर्डर',
      'Call Now': 'आता कॉल करा',
      'Monthly Orders': 'मासिक ऑर्डर',
      'Select Month': 'महिना निवडा',
      'Total Month': 'एकूण महिना',
      'Pay Now': 'आता पेमेंट करा',
      'Total Amount': 'एकूण रक्कम',
      'Total Quantity': 'एकूण प्रमाण',
      'Daily Orders': 'दैनंदिन ऑर्डर',
      'Filter by Product': 'उत्पादनानुसार फिल्टर करा',
      'All Products': 'सर्व उत्पादने',
      'No orders found for the selected month.': 'निवडलेल्या महिन्यासाठी कोणतेही ऑर्डर आढळले नाहीत।',
      'Total Orders': 'एकूण ऑर्डर',
      'Product': 'उत्पादन',
      'Qty': 'प्रमाण',
      'Price': 'किंमत',
      'Amount': 'रक्कम',
      'Customer': 'ग्राहक',
      'Day Total': 'दिवसाचा एकूण',
      'Today': 'आज',

      // Service Requests Page
      'Service Requests': 'सेवा विनंती',
      'Track your custom pricing requests': 'तुमच्या कस्टम किंमतीच्या विनंत्या ट्रॅक करा',
      'Back to Your Doodhwala': 'तुमच्या दूधवाल्याकडे परत जा',
      'No Service Requests': 'कोणत्याही सेवा विनंत्या नाहीत',
      'You haven\'t made any service requests yet. Request custom pricing from your assigned milkman.': 'तुम्ही अजून कोणत्याही सेवा विनंत्या केल्या नाहीत। तुमच्या नियुक्त दूधवाल्याकडून कस्टम किंमतीची विनंती करा।',
      'Go to Your Doodhwala': 'तुमच्या दूधवाल्याकडे जा',
      'Service Request': 'सेवा विनंती',
      'Requested on': 'विनंती केली',
      'Requested Services': 'विनंती केलेल्या सेवा',
      'Your Notes': 'तुमच्या नोंदी',
      'Milkman\'s Response': 'दूधवाल्याचा प्रतिसाद',
      'Total Quote': 'एकूण कोटेशन',
      'Accept Quote': 'कोटेशन स्वीकारा',
      'Reject Quote': 'कोटेशन नाकारा',
      'Pending': 'प्रलंबित',
      'Quote Received': 'कोटेशन मिळाले',
      'Accepted': 'स्वीकारले',
      'Rejected': 'नाकारले',

      'Waiting for milkman response...': 'दूधवाल्याच्या प्रतिसादाची वाट पाहत आहे...',
      'Quote provided on': 'कोटेशन दिले',
      'Accepted on': 'स्वीकारले',
      'Rejected on': 'नाकारले',
      'Quote Accepted!': 'कोटेशन स्वीकारले!',
      'The milkman has been notified of your acceptance.': 'दूधवाल्याला तुमच्या स्वीकृतीची सूचना देण्यात आली आहे।',
      'Quote Rejected': 'कोटेशन नाकारले',
      'The milkman has been notified of your decision.': 'दूधवाल्याला तुमच्या निर्णयाची सूचना देण्यात आली आहे।',
    }
  };

  return translations[language]?.[text] || text;
};