// DOOODHWALA — Customer Terms & Conditions (India).
//
// Source of truth for the text shown on the in-app acceptance screen and on
// the public /terms page. Editing this file is how the terms get amended —
// bump CUSTOMER_TERMS_VERSION when the text changes materially, and give
// users the notice period required by clause 18.1 before the change is live.
//
// The "Implementation checklist" from the source draft is deliberately not
// included here: it is internal guidance addressed to the operator, and the
// draft instructs that it be deleted before publishing.

export const CUSTOMER_TERMS_VERSION = "customer-2026-08-29";
export const CUSTOMER_TERMS_LAST_UPDATED = "29 August 2026";

export const CUSTOMER_TERMS_MARKDOWN = `
# DOOODHWALA — Terms and Conditions (Customer)
Operated by: Sambhavshri Agro Processing LLP LLPIN: ACB - 4950, registered office at 11/D, Pagariya Residency, Vedant Nagar, Chhatrapati Sambhaji Nagar. ("DOOODHWALA", "Platform", "we", "us").
## 1. Acceptance and nature of this agreement
1.1 These Terms, together with the Privacy Policy, Refund & Cancellation Policy and any policy published on the Platform, constitute a legally binding electronic agreement between you ("Customer", "you") and DOOODHWALA.
1.2 This is an electronic record generated by a computer system and published in accordance with the Information Technology Act, 2000 and the rules made thereunder, including Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. It does not require any physical, digital or electronic signature and is enforceable under Section 10A of the Information Technology Act, 2000.
1.3 By registering, clicking "I agree", or placing or receiving any order, you signify your unconditional acceptance of these Terms.
1.4 If you do not agree, you must not use the Platform.
## 2. Eligibility
2.1 You must be a person competent to contract under Section 11 of the Indian Contract Act, 1872 — i.e. at least 18 years of age, of sound mind, and not disqualified from contracting by any law.
2.2 If you are below 18, you may use the Platform only through a parent or lawful guardian who accepts these Terms on your behalf and is responsible for all activity on the account.
2.3 The Platform is intended for use within the territory of India only.
## 3. Role of the Platform — Intermediary and Marketplace
3.1 DOOODHWALA is a technology platform that connects Customers with independent milk suppliers, dairies, distributors and delivery persons ("Milkman" / "Supplier"). We do not own, produce, process, pack, store or sell milk or dairy products.
3.2 DOOODHWALA is an "intermediary" under Section 2(1)(w) of the Information Technology Act, 2000 and a "marketplace e-commerce entity" under the Consumer Protection (E-Commerce) Rules, 2020. We claim the exemption from liability available under Section 79 of the Information Technology Act, 2000.
3.3 The contract for sale and supply of milk and dairy products is directly between you and the Supplier. DOOODHWALA is not a party to that contract and does not give any warranty, express or implied, regarding the goods.
3.4 In compliance with Rule 5 of the Consumer Protection (E-Commerce) Rules, 2020, the Platform will make available to you, on request or through the app, the Supplier's legal name, principal geographic address, contact details and FSSAI licence/registration number.
3.5 We do not adopt any unfair trade practice, do not manipulate prices to gain unreasonable profit, and do not discriminate between Customers of the same class.
## 4. Registration and account security
4.1 You must provide information that is true, accurate, current and complete, and keep it updated.
4.2 You are solely responsible for maintaining the confidentiality of your login credentials, OTPs and device, and for all activity under your account.
4.3 Notify us immediately at sambhavshriagroprocessing@gmail.com of any unauthorised use. DOOODHWALA is not liable for loss arising from your failure to safeguard credentials.
4.4 We may verify your mobile number, address or identity, and may suspend or terminate accounts containing false, misleading or fraudulent information.
## 5. Orders, subscriptions and cutoff
5.1 Milk quantity, product type and delivery schedule may be created, modified or paused through the Platform.
5.2 All changes, pauses and cancellations must be submitted before the daily cutoff time displayed in the app for your Supplier. Requests received after cutoff will ordinarily take effect from the next delivery cycle.
5.3 A subscription is a standing instruction to deliver until you pause or cancel it. You remain liable for deliveries actually made against a subscription you did not pause before cutoff.
5.4 Prices are displayed inclusive of applicable taxes unless stated otherwise. GST, where applicable, will be charged and invoiced in accordance with the Central Goods and Services Tax Act, 2017 and rules thereunder.
5.5 Quantity and measurement of products shall comply with the Legal Metrology Act, 2009 and the Legal Metrology (Packaged Commodities) Rules, 2011. Declarations on pre-packaged products are the responsibility of the Supplier/packer.
## 6. Delivery
6.1 Delivery timings are indicative and may vary with the Supplier's route, traffic, weather, local restrictions and other conditions.
6.2 You must ensure safe and reasonable access for delivery and, where required, that a person is available to receive the delivery.
6.3 If you have instructed unattended delivery (e.g. at a doorstep, gate or milk box), risk in the goods passes to you upon such delivery, and neither DOOODHWALA nor the Supplier is responsible for theft, spoilage or tampering thereafter.
6.4 Repeated non-acceptance of delivery may result in suspension of the subscription and recovery of amounts due for goods actually delivered.
## 7. Product quality, food safety and complaints
7.1 Milk and dairy products supplied through the Platform are required to comply with the Food Safety and Standards Act, 2006, the Food Safety and Standards (Food Products Standards and Food Additives) Regulations, 2011, and the Food Safety and Standards (Licensing and Registration of Food Businesses) Regulations, 2011.
7.2 Every Supplier onboarded on the Platform is required to hold and maintain a valid FSSAI licence or registration. Responsibility for food safety, hygiene, adulteration, cold chain, standards of quality and statutory labelling rests solely with the Supplier as the Food Business Operator.
7.3 Report any quality complaint within 24 hours of delivery through the app, with the order details and, where possible, photographs and retention of the product/packaging. Complaints raised after 24 hours may not be capable of verification.
7.4 On a verified complaint, the Supplier will provide replacement or credit/refund in accordance with the Refund & Cancellation Policy. Refunds, where payable, will be processed to the original payment method within 7 business days of approval.
7.5 Nothing in these Terms restricts your statutory rights against the Supplier under the Consumer Protection Act, 2019, or the powers of authorities under the Food Safety and Standards Act, 2006.
## 8. Payments and billing
8.1 You agree to pay all amounts due on or before the due date shown in the app.
8.2 Payments are processed through third-party payment gateways/aggregators authorised by the Reserve Bank of India under the Payment and Settlement Systems Act, 2007. DOOODHWALA does not store your full card, CVV or banking credentials; card data handling follows RBI's tokenisation framework.
8.3 Payment gateway failures, network errors, refund timelines and chargebacks are governed by the policies of the relevant bank, aggregator and card network. Amounts debited without a successful order will be reversed as per those policies.
8.4 Any advance or wallet balance held is a prepaid deposit against future deliveries only. It is non-transferable, cannot be withdrawn as cash, and is not a deposit under the Banking Regulation Act, 1949.
8.5 Late payment may attract suspension of service after 3 days and late fee may charge @ 2% per month on overdue amounts, subject to applicable law.

8.6 GST-compliant invoices will be issued by the Supplier or by the Platform on the Supplier's behalf, as applicable.

8.7 Platform fee. In addition to the price of the products supplied by the Supplier, DOOODHWALA charges a platform fee of 1% (one per cent) of the order value for the use of the Platform. This fee is charged by DOOODHWALA, is not payable to or received by the Supplier, and is shown as a separate line on your bill before you make payment.

8.8 Applicable GST on the platform fee will be charged and invoiced in accordance with the Central Goods and Services Tax Act, 2017.

8.9 Where an order is cancelled or refunded in full, the platform fee charged on that order is refunded with it. Where a partial refund is made, the platform fee is reduced proportionately.

8.10 We may revise the platform fee. Any revision will be notified through the app at least 7 days before it takes effect, and will apply only to orders placed on or after the effective date.
## 9. Pause, cancellation and account closure
9.1 You may pause deliveries through the app before the daily cutoff time.
9.2 You may discontinue the service at any time by cancelling the subscription in the app and informing the Milkman.
9.3 All outstanding dues must be cleared before account closure. Closure does not extinguish liability for goods already delivered.
9.4 We may suspend or terminate your account, with notice were reasonably practicable, for non-payment, breach of these Terms, fraud, abuse of delivery personnel, or where required by law or a court/government order.
## 10. User conduct and prohibited content
10.1 You shall not:
- provide false, misleading or impersonating information;
- abuse, threaten, harass or endanger the Milkman or delivery personnel;
- misuse, reverse-engineer, scrape, overload or attempt unauthorised access to the Platform;
- use the Platform for any unlawful purpose, money laundering or resale/commercial redistribution without written consent;
- infringe any intellectual property or third-party right.
10.2 In accordance with Rule 3(1)(b) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, you shall not host, display, upload, publish or share any information which: belongs to another person and to which you do not have rights; is obscene, paedophilic, invasive of privacy, insulting or harassing on the basis of gender, racially or ethnically objectionable, or otherwise unlawful; harms a child; infringes intellectual property; deceives or misleads as to origin; impersonates another; threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order; contains software viruses; or is patently false with the intent to mislead.
10.3 On becoming aware of non-compliance, we may remove or disable access to such information and terminate access rights, and we will comply with lawful orders of a court or authorised government agency.
## 11. Privacy and personal data
11.1 We process personal data in accordance with our Privacy Policy, the Digital Personal Data Protection Act, 2023, and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011.
11.2 DOOODHWALA acts as a Data Fiduciary. We collect your name, mobile number, delivery address, geo-location (where enabled), order history and payment references for the purpose of providing dairy delivery services, billing, customer support and legal compliance.
11.3 Your data is shared with the Supplier and delivery personnel strictly to fulfil deliveries, and with payment processors to process transactions. We do not sell personal data to third parties.
11.4 As a Data Principal, you have the right to access a summary of your personal data, to correction and erasure, to grievance redressal, and to nominate another individual to exercise your rights in the event of death or incapacity. Requests may be made to the contact in Clause 13.
11.5 You may withdraw consent at any time, with the consequence that we may be unable to continue providing the service. Withdrawal does not affect processing carried out before withdrawal.
11.6 We retain personal data only as long as necessary for the stated purpose or as required by law, and apply reasonable security safeguards to prevent personal data breaches.
## 12. Intellectual property
The Platform, its software, trademarks, logos, designs, content and databases are owned by or licensed to DOOODHWALA and are protected under the Copyright Act, 1957, the Trade Marks Act, 1999 and other applicable laws. No right is granted to you except a limited, revocable, non-exclusive, non-transferable licence to use the app for personal use.
## 13. Grievance Redressal Officer
In compliance with Rule 3(2) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, Rule 4 of the Consumer Protection (E-Commerce) Rules, 2020, and Section 13 of the Digital Personal Data Protection Act, 2023:
- Name: Sachin Sancheti
- Designation: Chief Executive Officer
- Address: 2, Costa Mapple, New Osmanpura, Ner SSC Board, Chhatrapati Sambhajinagar -431005.
- Email: sambhavshriagroprocessing@gmail.com
- Phone: 8308804099
- Hours: Mon–Sat, 9:00–18:00 IST
13.1 Complaints will be acknowledged within 24 hours and disposed of within 15 days of receipt, in accordance with the IT Rules, 2021.
13.2 Consumer complaints under the Consumer Protection (E-Commerce) Rules, 2020 will be acknowledged within 48 hours and redressed within one month of receipt.
13.3 Requests to remove unlawful content covered by Rule 3(2)(b) of the IT Rules, 2021 will be acted upon within 24 hours.
13.4 You may also register a complaint on the National Consumer Helpline (1915) or the INGRAM portal, or with the appropriate Consumer Commission.
## 14. Force majeure
Neither party shall be liable for failure or delay in performance caused by events beyond reasonable control, including acts of God, flood, fire, epidemic or pandemic, government orders or lockdowns, strikes, riots, curfew, war, failure of transport or telecommunications, power failure, or cattle/livestock disease outbreaks affecting supply.
## 15. Limitation of liability
15.1 DOOODHWALA is not responsible for: the quality, quantity, safety, or legality of products supplied by the Supplier; delivery delays caused by circumstances beyond its control; disputes or transactions concluded outside the Platform; or the conduct of any Supplier, Milkman or Customer.
15.2 Subject to Clause 15.3, and to the extent permitted by law, DOOODHWALA's aggregate liability arising out of or in connection with these Terms shall not exceed the total Platform charges/commission actually received by DOOODHWALA in respect of your orders in the three (3) months preceding the event giving rise to the claim.
15.3 Nothing in these Terms excludes or limits liability which cannot lawfully be excluded, including liability for death or personal injury caused by negligence, for fraud, or any liability arising under the Consumer Protection Act, 2019 or the Food Safety and Standards Act, 2006.
15.4 Neither party shall be liable for indirect, incidental, special, punitive or consequential loss, or loss of profit, goodwill or data.
## 16. Indemnity
You agree to indemnify and hold harmless DOOODHWALA, its directors, officers and employees from any claim, demand, loss, penalty or expense (including reasonable legal fees) arising from your breach of these Terms, your violation of any law, or your infringement of any third-party right.
## 17. Governing law, dispute resolution and jurisdiction
17.1 These Terms are governed by and construed in accordance with the laws of India.
17.2 The parties shall first attempt to resolve any dispute amicably through the Grievance Redressal Officer within 30 days.
17.3 Failing amicable resolution, the dispute shall be referred to arbitration by a sole arbitrator appointed by mutual consent, under the Arbitration and Conciliation Act, 1996. The seat and venue of arbitration shall be Chhatrapati Sambhaji Nagar, Maharashtra, and the language shall be English. The award shall be final and binding.
17.4 Subject to the above, the courts at Chhatrapati Sambhaji Nagar, Maharashtra shall have exclusive jurisdiction.
17.5 **Consumer rights preserved: ** Nothing in Clauses 17.3 and 17.4 restricts your right as a consumer to approach the District, State or National Consumer Disputes Redressal Commission having jurisdiction, including the Commission where you ordinarily reside or work, under Section 34(2)(d) of the Consumer Protection Act, 2019.
## 18. Amendments, notices and general:
18.1 We may amend these Terms at any time. Material changes will be notified through the app, email or SMS at least 7 days in advance. Continued use after the effective date constitutes acceptance.
18.2 Notices to you may be sent by in-app notification, SMS or email to your registered details.
18.3 If any provision is held invalid or unenforceable, the remaining provisions continue in full force.
18.4 Our failure to enforce any right is not a waiver of that right.
18.5 You may not assign your rights under these Terms. We may assign to an affiliate or successor on notice.
18.6 These Terms, with the policies referred to in Clause 1.1, constitute the entire agreement between you and DOOODHWALA regarding the Platform.
18.7 In case of conflict between the English version and any translation, the English version prevails.
`.trim();
